name: system 
description: Invoke operating system commands. Exposes `system()` on macOS &
  Linux. Uses `dart:ffi`.
version: 0.3.0
author: miksen.dk
homepage: https://github.com/miksen/system

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
  ffi: ^0.2.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
