name: system 
description: Invoke operating system commands. Exposes `system()` on macOS &
  Linux. Uses `dart:ffi`.
version: 0.1.0
# author: Michael Thomsen <m@svth.dk>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  ffi: ^0.1.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
